# Generated by Django 4.2.1 on 2023-06-07 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('species', models.CharField(choices=[('a', 'Unicorn'), ('b', 'Bear'), ('c', 'Cat'), ('d', 'Dinosaur')], default='a', max_length=1)),
                ('color', models.CharField(choices=[('1', 'Green'), ('2', 'Pink'), ('3', 'Purple'), ('4', 'Grey'), ('5', 'Yellow')], default='1', max_length=1)),
                ('bio', models.TextField(max_length=1000)),
                ('age', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('food', models.CharField(choices=[('food1', 'Burger'), ('food2', 'KaleSoup'), ('food3', 'Donut')], default='food1', max_length=6)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.pet')),
            ],
        ),
    ]
