# Generated by Django 4.2.1 on 2023-06-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='image',
        ),
        migrations.AddField(
            model_name='pet',
            name='colors',
            field=models.CharField(choices=[('1', 'Green'), ('2', 'Pink'), ('3', 'Purple'), ('4', 'Grey'), ('5', 'Yellow')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('A', 'Unicorn'), ('B', 'Bear'), ('C', 'Cat'), ('D', 'Dinosaur')], default='A', max_length=1),
        ),
    ]
