# Generated by Django 4.2.1 on 2023-06-08 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_pet_options'),
        ('main_app', '0006_rename_cat_photo_pet'),
    ]

    operations = [
    ]
